apiVersion: v1
kind: Service
metadata:
  name: shoppingcartapp-local
  annotations:
    "prometheus.io/scrape": "true"
    "prometheus.io/scheme": http
    "prometheus.io/path": "/metrics"
    "prometheus.io/port": "9001"
spec:
  ports:
    - name: metrics
      protocol: TCP
      port: 9001
      targetPort: 9001
---
apiVersion: v1
kind: Endpoints
metadata:
  name: shoppingcartapp-local
subsets:
  - addresses:
      -  ip: 192.168.99.1
    ports:
      - name: metrics
        protocol: TCP
        port: 9001
